[workspace]
members = ["aiscript", "aiscript-cli", "aiscript-runtime", "aiscript-vm"]
exclude = []
resolver = "2"

# [[bin]]
# name = "aiscript-cli"
# path = "aiscript-cli/src/main.rs"

# [[bin]]
# name = "aiscript-runtime"
# path = "aiscript-runtime/src/main.rs"

[workspace.package]
edition = "2021"
repository = "https://github.com/aiscriptdev/aiscript"
license = "Apache-2.0"

[workspace.dependencies]

# RUSTFLAGS="-Z sanitizer=address" cargo run --release --target x86_64-apple-darwin -- test.ai
[profile.release]
debug = true
