site_name: AiScript
# repo_url: https://github.com/aiscript-dev/aiscript
# repo_name: aiscript-dev/aiscript
copyright: Copyright &copy; 2024 AiScript

nav:
  - Home: 
    - Welcome: index.md
    - Installation: installation.md
    - Philosophy: philosophy.md
    - FAQ: faq.md
  - Get started:
    - Setup: get-started/setup.md
    - Define model: get-started/define-model.md
    - User API: get-started/user-api.md
    - Define schema: get-started/define-schema.md
    - Tweet API: get-started/tweet-api.md
    - Aunthentication: get-started/authentication.md
  - Concepts:
    - Overview: concepts/overview.md
    - Route: concepts/route.md
    - Model: concepts/model.md
    - Schema: concepts/schema.md
    - Validator: concepts/validator.md
    - Middleware: concepts/middleware.md
    - Migration: concepts/migration.md
  - References:
    - Language syntax: references/syntax.md
    - Language keywords: references/keywords.md
    - Data types: references/types.md
    - Route request: references/request.md
    # - Auto model conventions: references/auto-model.md
    - Standard library:
      - prelude: references/stdlib/prelude.md
      - std.array: references/stdlib/array.md
      - std.env: references/stdlib/env.md
      - std.str: references/stdlib/str.md
      - std.math: references/stdlib/math.md
      - std.io: references/stdlib/io.md
      - std.http: references/stdlib/http.md
      - std.time: references/stdlib/time.md
      - std.security: references/stdlib/security.md
      - std.random: references/stdlib/random.md
    - Directives: references/directives.md
    - Configuration:
      - General: references/configuration/general.md
      - Database: references/configuration/database.md
      - Middleware: references/configuration/middleware.md
      - Security: references/configuration/security.md
      - Obersevability: references/configuration/observability.md
    - aim reference: references/aim.md

theme:
  name: material
  palette:
    primary: red
  features:
  - announce.dismiss
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  # - content.code.select
  # - content.footnote.tooltips
  # - content.tabs.link
  - content.tooltips
  # - header.autohide
  # - navigation.expand
  - navigation.footer
  - navigation.indexes
  # - navigation.instant
  # - navigation.instant.prefetch
  # - navigation.instant.progress
  # - navigation.prune
  # - navigation.sections
  - navigation.tabs

markdown_extensions:
  - pymdownx.superfences
  # - pymdownx.inlinehilite
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
