[package]
name = "xtask"
version = "0.1.0"
edition.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5", features = ["derive"] }
