[package]
name = "aiscript-vm"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8"
gc-arena = { git = "https://github.com/kyren/gc-arena", rev = "3dbc6c4263700312ef63ceee3f02943b38828130", features = [
    "allocator-api2",
    "hashbrown",
] }
# gc-arena = { path = "../../gc-arena", features = ["allocator-api2", "hashbrown"] }
hashbrown = { version = "0.14", features = ["raw"] }
openai-api-rs = { git = "https://github.com/aiscriptdev/openai-api-rs.git", rev = "568f41b74f0e0443814b74810fa31a37bed9c7d2" }
num_enum = "0.7.3"
serde_json = "1.0.132"
tokio = { version = "1.41.0" }
indexmap = "2.6.0"
chrono = "0.4.38"
regex = "1.11.1"

[features]
# Enable debug features.
debug = []
# For testing AI
ai_test = []
