[package]
name = "aiscript-vm"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8"
gc-arena = { git = "https://github.com/kyren/gc-arena", rev = "3dbc6c4263700312ef63ceee3f02943b38828130", features = [
    "allocator-api2",
    "hashbrown",
] }
# gc-arena = { path = "../../gc-arena", features = ["allocator-api2", "hashbrown"] }
hashbrown = { version = "0.14", features = ["raw"] }
openai-api-rs = { git = "https://github.com/aiscriptdev/openai-api-rs.git", rev = "2a541a3f6fb826ac655d42bb83deb28a89e75938" }
num_enum = "0.7.3"
serde_json = "1.0.132"
tokio = { version = "1.41.0" }
indexmap = "2.6.0"

[features]
# v1 one-pass compiler
v1 = []
# Enable debug features.
debug = []
# For testing AI
ai_test = []
