[package]
name = "aiscript-vm"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8"
gc-arena = { version = "0.5.3", features = ["allocator-api2", "hashbrown"] }
hashbrown = { version = "0.14", features = ["raw"] }
num_enum = "0.7.3"

[features]
# Enable debug features.
debug = []
